"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Provider } from "react-redux";
import { store } from "./store";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

import { useRouter } from "next/navigation";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "TodoList React",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();

  const goToPage = (url: string): void => {
    router.push(`/${url}`);
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="todoapp">
          <header className="header">
            <h1>todos</h1>
            <div className="link">
              <a onClick={() => goToPage("todo")}>Todo</a>
              <a onClick={() => goToPage("list")}>List</a>
            </div>
          </header>
          <Provider store={store}>
            <div className="main">{children}</div>
          </Provider>

        </section>
      </body>
    </html>
  );
}
