import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TodoList React",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="todoapp">
          <header className="header">
            <h1>todos</h1>
            <div className="link">
              {/* <a [routerLink]="['/todo']" routerLinkActive="router-link-active">Add</a> */}
              {/* <a [routerLink]="['/list']" routerLinkActive="router-link-active">List</a> */}
            </div>
          </header>
          <div className="main">{children}</div>
        </section>
      </body>
    </html>
  );
}
